spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/inshorts"
    username: root
    password: root

server:
  error:
    include-message: always